### ISSUE TITLE
Getting 401 response when trying to acquire XToken

### ISSUE THREAD

**Issue by aevir** [OpenXbox/xbox-webapi-csharp#15]
Hello, I am trying the following:

```
var headlessAuthService = new HeadlessAuthenticationService(requestUrl);
var response = await headlessAuthService.AuthenticateAsync("<email>", "<password>");
var authenticator = new AuthenticationService(response);
bool success = await authenticator.AuthenticateAsync();
```

When the above code runs, the response contains an AccessToken and a RefreshToken, as well as the UserId. 

However, authentication fails when it tries to get the XToken using AuthenticateXSTSAsync method. There, the response returns 401 (unauthorized). 

Do you have any clue what might be the issue?

Thanks in advance!

**Comment by tuxuser** [comment]
Cannot confirm.

Tested on latest `master`:

```cs
var requestUrl = AuthenticationService.GetWindowsLiveAuthenticationUrl();
var headlessAuthService = new HeadlessAuthenticationService(requestUrl);
var response = await headlessAuthService.AuthenticateAsync("<email>", "<password>");
var authenticator = new AuthenticationService(response);
bool success = await authenticator.AuthenticateAsync();
Console.WriteLine(authenticator.XToken);
```

```text
dotnet run -p XboxWebApi.Cli/
<XboxWebApi.Authentication.XToken Jwt=ey..., Issued=9/12/2020 11:25:50 AM, Expires=9/13/2020 3:25:50 AM>
```

**QUESTION**: are you using the requestUrl returned by `AuthenticationService.GetWindowsLiveAuthenticationUrl();` ?

**Comment by aevir** [comment]
Yes, I get it from `string requestUrl = AuthenticationService.GetWindowsLiveAuthenticationUrl();`

I tried with 2 different accounts and I also used the python module, as well as the workflow mentioned here: https://gist.github.com/tuxuser/8b7cc153cdecd0a9c3f2694850fa90bd but ran into the same issue every time. 

Maybe it is related to some account-level restriction

**Comment by tuxuser** [comment]
Yeah that's very likely the issue, your accounts requesting some sort of additional / manual confirmation action.
