### ISSUE TITLE
Configuration Errors

### ISSUE THREAD

**Issue by discoderpin** [OpenXbox/xbox-webapi-csharp#16]
After successfully authenticating with my web app, I'm unable to use any of the Service types. 
`The format of value 'XBL3.0 '...' is invalid.`

Also when using project XboxWebApi.Cli. _(Headless + Token path)_ set.
`Authentication succeeded`
`Headless authentication failed, error: Input string was not in a correct format.`

**Comment by tuxuser** [comment]
Fixed in v0.3.1, thanks @damirarh
