### ISSUE TITLE
why is this whole thing only working with client-id 0000000048093EE3 ??

### ISSUE THREAD

**Issue by michabbb** [OpenXbox/xbox-webapi-csharp#2]
pardon if i point to another project, but i am a totally desperate and searching for answers. please take a look [to my problem](https://github.com/OpenXbox/xbox-webapi-python/issues/6), thanks !!!

**Comment by tuxuser** [comment]
We have webhooks running, we are seeing all issues in the second they arrive ;)
**[CLOSED]**
