### ISSUE TITLE
System.IO.InvalidDataException: 'Invalid URL to parse: <Received Redirection URL>'

### ISSUE THREAD

**Issue by ClonkAndre** [OpenXbox/xbox-webapi-csharp#22]
I would like to use this api, is there a way to fix this?

**Comment by criptem** [comment]
I believe that's just placeholder text, you have to actually visit the url generated by AuthenticationService.GetWindowsLiveAuthenticationUrl() and get the url that it changes into.  You place the new url into where it currently says " Received Redirection URL> ", and it'll work fine.  

I did this by creating a WebView, navigating to the webview with the first url, then grabbing the new url from the WebView's source and then parsing the url with AuthenticationService.ParseWindowsLiveResponse(newurl as string), and turning that into a WindowsLiveResponse variable, which I then fed into a new AuthenticationService.

**Comment by ClonkAndre** [comment]
Oh that was very useful! It worked now! Thank you so much 🙂
