### ISSUE TITLE
How can I log in as a specifc user?

### ISSUE THREAD

**Issue by aaron-bond** [OpenXbox/xbox-webapi-csharp#3]
Hi there, thanks for this - it's a great resource.

I have a back-end service I'm looking to use to retrieve Xbox game clips via the Xbox Live Services REST endpoints but I can't figure out how to use this library to connect using a MS Content Creator account.

However, all the samples look like they require passing along the URL to a user to allow them to log in, rather than passing along pre-defined login info. Any help is much appreciated!

**Comment by tuxuser** [comment]
To get this right: You want to do headless authentication?
It is not implemented right now cause Oauth2 really is the safer / more fail proof way to do it. If you want to do it anyways, take a look at xbox-webapi-python repository. 

If it's about getting your own Xuid/Gamertag after authentication: Gets stored in AuthenticationService.UserInformation

**Comment by aaron-bond** [comment]
Yeah I just want to grab a feed of game clips right now and feed it back to a web page

Edit: to be clear - I'm creating a simple rest endpoint which can serve up any gamer's public clips. The endpoint it self can be hit anonymously but then it'll go to the Xbox services to grab the feed after logging in as some account I've predetermined

**Comment by tuxuser** [comment]
Here you can see the gameclips API, implemented in python:
https://github.com/OpenXbox/xbox-webapi-python/blob/master/xbox/webapi/api/provider/gameclips.py

Feel free to send a PR - just take a look at the other services, how stuff should be implemented (request queries, response models)

**Comment by aaron-bond** [comment]
Will do!

**Comment by aaron-bond** [comment]
@tuxuser not sure whether this is the right place for this, but I'm attempting to re-implement [this](https://github.com/OpenXbox/xbox-webapi-python/blob/3f134d3688aa6f372a06a9f0c10f4143a9cc75a8/xbox/webapi/authentication/manager.py#L442) function in my application / porting it into this project if you want it.

I've hit a bit of a roadblock though. The GET authentication request (coming out of GetWindowsLiveAuthenticationUrl()) will write back a single cookie when I call it from code (the `MSPRequ` one), but will write 3 cookies when I call it from Postman (including the `uaid` one that I need).

Have you ever run into this issue / have any ideas what I could be doing wrong?

**Comment by tuxuser** [comment]
@aaron-bond You are correct, I was able to verify mentioned behaviour:

Test code (additional constructor for AuthenticationManager)
```cs
public AuthenticationService(string email, string password)
{
    RestClientEx client = ClientFactory("https://login.live.com");
    RestRequestEx request = new RestRequestEx("oauth20_authorize.srf", Method.GET);
    NameValueCollection nv = new Model.WindowsLiveAuthenticationQuery().GetQuery();
    request.AddQueryParameters(nv);
    client.FollowRedirects = false;

    IRestResponse resp = client.Execute(request);
    if (resp.StatusCode == HttpStatusCode.Found)
    {
        Console.WriteLine("Already authenticated...");
    }

    Console.WriteLine("Response cookies: {0}", resp.Cookies.Stringify());
}
```

Console output
```
Response cookies: <List`1 [{"Comment":"","CommentUri":null,"Discard":false,"Domain":"login.live.com","Expired":false,"Expires":"0001-01-01T00:00:00","HttpOnly":false,"Name":"MSPRequ","Path":"/","Port":"","Secure":false,"TimeStamp":"2018-10-01T16:07:18.792441+02:00","Value":"lt=<some-number>&co=1&id=N","Version":1}]>
```

Actual cookie section however returns the following, full data:
```
Set-Cookie=MSPRequ=lt=<some-number>&co=1&id=N; secure= ;path=/;HTTPOnly=;version=1, uaid=<some-uaid>; domain=login.live.com;secure= ;path=/;HTTPOnly= ;version=1, MSPOK=$uuid-<some-uuid>; domain=login.live.com;secure= ;path=/;HTTPOnly= ;version=1
```

It looks like a RestSharp bug, related to cookie parsing, to me :/

Updated the issue for RestSharp here: https://github.com/restsharp/RestSharp/issues/545#issuecomment-425940431
