### ISSUE TITLE
Documentation update needed -- PresenceService (etc) example.

### ISSUE THREAD

**Issue by ericjpeters** [OpenXbox/xbox-webapi-csharp#6]
I am trying to this code for the first time -- so far, it looks great!  Super clean interfaces, easy to navigate, and very intuitive.

However, on the main page, the brief example for PresenceService (also PeopleService and MessageService) show a constructor which takes a single argument: xblConfig.   However, the real constructor also takes a IRestSharpEx object -- which is trivial to create, but it's not clear what the base URL should be for that httpClient.

Can that small example be updated to show us an appropriate base URL for these API's?  Thanks so much!!

**Comment by tuxuser** [comment]
v0.3.0 has the fixed README :+1:
