### ISSUE TITLE
Adding scope into Microsoft app registration

### ISSUE THREAD

**Issue by hamed-estsoft** [OpenXbox/xbox-webapi-csharp#7]
Hi.
I would really appreciate if you help me with my problem. When i replace the **Client_id & redirect_url** in  the **requestUrl** ,  when i open the url it gives me the error below :
**error=invalid_scope&error_description=The+provided+value+for+the+input+parameter+'scope'+has+not+been+pre-authorized+for+this+client+application.**

I'm not sure where i should add the **scope=service::user.auth.xboxlive.com::MBI_SS**

I have already registered my app in microsoft app registration and here is the url that i'm trying to run:
**https://login.live.com/oauth20_authorize.srf?response_type=token&scope=service::user.auth.xboxlive.com::MBI_SSL&redirect_uri=https://localhost:44331/signin&client_id=8e425872-a8d3-4882-83ab-582a485c891a&display=touch&locale=en**

**Comment by tuxuser** [comment]
I think with when you supply custom `client_id` you need to set `response_type` to `code`. Token is not supported.
And yeah, you need another scope indeed, like the error suggests.

Correct me if wrong but it seems you need an ID@Xbox registration to get an xbox live entitled authentication going.

**Comment by tuxuser** [comment]
Closing for now, as its not really an issue with the client but with the API / app service registration.

Related to: https://github.com/OpenXbox/xbox-webapi-python/issues/6

**Comment by tuxuser** [comment]
https://gist.github.com/tuxuser/8b7cc153cdecd0a9c3f2694850fa90bd
